services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant_data:/qdrant/storage
  postgresql:
    container_name: postgres
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecret
    volumes:
      - ./init-postgresql:/docker-entrypoint-initdb.d

  api-gateway:
    image: nginx:1.29
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - NGINX_HOST=api-gateway
      - YANDEX_LLM_URL=https://llm.api.cloud.yandex.net
      - GENERATION_SERVICE_URL=http://augmented-generation:8082

configs:
  qdrant_config:
    content: |
      log_level: INFO

networks:
  ai-network:
    driver: bridge
