[project]
name = "llm-audit"
version = "0.1.0"
description = "This is a service for auditing the work of RAG"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flasgger>=0.9.7.1",
    "flask>=3.1.2",
    "python-dotenv>=1.2.1",
    "yandex-cloud-ml-sdk>=0.16.0",
]